title: Radio4000 Legal
description: Public legal documents for Radio4000
theme: minima

# Custom domain settings
domain: legal.radio4000.com
url: https://legal.radio4000.com

# Optional: Uncomment to use a different GitHub Pages supported theme
# theme: jekyll-theme-minimal
# theme: jekyll-theme-cayman

# Exclude files from processing
exclude:
  - .git/
